spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**, /api/category/**
#          filters:
#            - StripPrefix=0
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/billing/**
#          filters:
#            - StripPrefix=2
#        - id: customer-service
#          uri: lb://customer-service
#          predicates:
#            - Path=/api/security/**


server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
